Repository ashishnagpal2498/hackstation, pull requests merged in 2021-01, with the labels that each got.

#13 Create Template for contribution
  .github/Issue_template/Bug_report.md
  .github/Issue_template/Feature_request.md
  .github/Pull_request_template.md
Labels: DWOC, Level-2, documentation

#14 update header styles
  frontend/src/components/layout/Navbar.js
  frontend/src/components/styles/Navbar.css
Labels: DWOC, Level-4, enhancement

#28 Update issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Beginner, SWOC21, documentation
