Repository ashishnagpal2498/hackstation, pull requests merged in 2021-02, with the labels that each got.

#33 Add logo and user icon in header
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/logo.png
  frontend/src/components/layout/Navbar.js
  frontend/src/components/styles/Navbar.css
  package-lock.json
Labels: Beginner, SWOC21, good first issue

#36 Upcoming Contest Card Component
  frontend/src/App.js
  frontend/src/components/layout/Card.js
  frontend/src/components/layout/Cards.js
  frontend/src/components/styles/Card.css
  frontend/src/components/styles/Cards.css
Labels: DWOC, Level-4, UI/UX

#45 MongoDB Backend
  backend/config/index.js
  backend/config/variables.json
  backend/helpers/dbConnection.js
  backend/server.js
Labels: Backend, DWOC, Level-4

#44 Added Charts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/layout/Cards.js
  frontend/src/components/layout/Charts.js
  frontend/src/components/styles/Charts.css
Labels: Hard, SWOC21, UI/UX

#43 #39 SignUp Component
  frontend/src/App.js
  frontend/src/components/layout/Navbar.js
  frontend/src/components/layout/SignUp.js
  frontend/src/components/styles/SignUp.css
  frontend/src/images/icon-error.svg
Labels: Medium, SWOC21, UI/UX

#49 Added contributor's table
  README.md
Labels: DWOC, Level-1, documentation

#50 Added proposed CSS
  frontend/src/Proposed.css
Labels: DWOC, Level-2
